name: Build Javascript
on:
  workflow_call:
    inputs:
      env:
        description: environment to build
        required: true
        type: string

env:
  NODE_VERSION: 16
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'read'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com
          scope: '@p00ls'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: yarn build:${{ inputs.env }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build_${{ inputs.env }}
          path: build
