name: Deploy env to bucket
on:
  workflow_call:
    inputs:
      env:
        description: environment to deploy
        required: true
        type: string
      ref:
        description: SHA1 to checkout
        required: false
        default: 'latest'
        type: string
    secrets:
      WORKLOAD_IDENTITY_PROVIDER:
        required: true
      DEX_GCLOUD_SA:
        required: true
      BUCKET_NAME:
        required: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    env:
      COMMIT_ID: ${{ inputs.ref == 'latest' && github.sha || inputs.ref }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.COMMIT_ID }}
      - name: Download Build artifact
        if: github.workflow == 'CI'
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Download Build artifact
        if: github.workflow != 'CI'
        uses: dawidd6/action-download-artifact@v2
        with:
          commit: ${{ env.COMMIT_ID }}
          workflow: ci.yaml
          name: build
          path: build
          workflow_conclusion: ""
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.DEX_GCLOUD_SA }}
      - name: Deploy
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'build'
          destination: ${{ secrets.BUCKET_NAME }}
          parent: false
